package io.tesseraql.yaml;

import tools.jackson.databind.DeserializationFeature;
import tools.jackson.databind.MapperFeature;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.cfg.EnumFeature;
import tools.jackson.databind.cfg.MapperBuilder;

/**
 * Jackson 2's value for every default Jackson 3 changed that an application would observe
 * (docs/jackson-3.md decision 4). Every mapper factory in and above this module builds through
 * {@link #pin}; {@code SecurityJson} and {@code McpJson} live below it and repeat these lines,
 * and {@code JacksonDefaultsLedgerTest} holds all of them to the same states.
 *
 * <p>The defaults Jackson 3 changed that nothing observes today — dates as ISO text, no field
 * views, getters not used as setters, fast float parsing — keep 3.x's value; the full verify
 * is the measurement that they stay unobserved.
 */
public final class JacksonDefaults {

    private JacksonDefaults() {
    }

    /** {@code builder} with the pinned states applied. */
    public static <M extends ObjectMapper, B extends MapperBuilder<M, B>> B pin(B builder) {
        return builder
                // An absent boolean in authored YAML means false: that is the authored contract,
                // and on 3.x's default every optional boolean record component refuses to load.
                .disable(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES)
                // Adopted on its own evidence in S2; until then a value is read as 2.x read it.
                .disable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS)
                // An unknown property stays a refusal. The authored models opt out class by class
                // and TQL-YAML-1043 owns unknown keys; relaxing it everywhere is silent tolerance.
                .enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                // Declaration order is the deterministic-output contract
                // (docs/deterministic-output.md): alphabetical would move every generated byte.
                .disable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
                // An enum's wire form is its name, as it was; toString() stays the enum's own.
                .disable(EnumFeature.READ_ENUMS_USING_TO_STRING)
                .disable(EnumFeature.WRITE_ENUMS_USING_TO_STRING);
    }
}
