package io.tesseraql.yaml.template;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * The bundled hc email fragment library (docs/notifications.md "HTML mail"): the
 * {@code tql/email/*} artifacts are generated by {@code @hypermedia-components/cli email
 * eject} and checked in — these tests are the drift guard (the regen command is in each
 * file's manifest comment), plus a render proof that the fragments resolve from an app's
 * mail template and that an app-home copy shadows the bundled library.
 */
class BundledEmailTemplatesTest {

    private static final Pattern FRAGMENT = Pattern.compile("th:fragment=\"(\\w+)");

    /** The documented palette — a regen that drops or renames a fragment fails here. */
    private static final Set<String> LIBRARY_FRAGMENTS = Set.of(
            "hcButton", "hcButtonSecondary", "hcHeading", "hcSubheading", "hcText",
            "hcTextMuted", "hcLink", "hcSeparator", "hcBadge", "hcBadgeInfo",
            "hcBadgeSuccess", "hcBadgeWarning", "hcBadgeError", "hcAlertInfo",
            "hcAlertSuccess", "hcAlertWarning", "hcAlertError", "hcPanel", "hcKvTable",
            "hcFooter");

    @Test
    void bundledLibraryCarriesTheExpectedFragmentsAndProvenance() {
        String library = bundled("hc-email.html");
        assertThat(fragments(library)).isEqualTo(LIBRARY_FRAGMENTS);
        assertThat(library).contains("Axes: color=default neutral=slate flavor=thymeleaf");

        String layout = bundled("hc-email-layout.html");
        assertThat(fragments(layout)).isEqualTo(Set.of("hcLayout"));
        assertThat(layout).contains("Axes: color=default neutral=slate flavor=thymeleaf");
    }

    @Test
    void mailTemplateComposesTheBundledFragments(@TempDir Path appHome) throws IOException {
        Files.createDirectories(appHome.resolve("templates/mail"));
        Files.writeString(appHome.resolve("templates/mail/notice.html"),
                """
                        <div th:replace="~{tql/email/hc-email-layout :: hcLayout('Notice',
                            |Hello ${payload.name}|, ~{:: content})}">
                          <div th:fragment="content">
                            <div th:replace="~{tql/email/hc-email :: hcHeading('Notice')}"></div>
                            <div th:replace="~{tql/email/hc-email :: hcText(|Hello ${payload.name}.|)}"></div>
                            <div th:replace="~{tql/email/hc-email :: hcButton(${payload.url}, 'Open')}"></div>
                          </div>
                        </div>
                        """);

        String html = Templates.render(appHome, "templates/mail/notice.html", Map.of(
                "payload", Map.of("name", "Suzuki", "url", "https://example.com/t/1")));

        // The layout shell wraps the content fragment once, styling stays inline, and the
        // wrapper's inline fragment definition is not emitted a second time.
        assertThat(html).contains("<title>Notice</title>");
        assertThat(html).containsOnlyOnce("Hello Suzuki.");
        assertThat(html).contains("href=\"https://example.com/t/1\"");
        assertThat(html).contains("background-color:#2563eb");
        assertThat(html).doesNotContain("th:replace");
    }

    @Test
    void appTemplatesShadowTheBundledLibrary(@TempDir Path appHome) throws IOException {
        Files.createDirectories(appHome.resolve("templates/tql/email"));
        Files.createDirectories(appHome.resolve("templates/mail"));
        Files.writeString(appHome.resolve("templates/tql/email/hc-email.html"), """
                <p th:fragment="hcText(text)" th:text="${text}" style="color:#123456;"></p>
                """);
        Files.writeString(appHome.resolve("templates/mail/notice.html"), """
                <div th:replace="~{tql/email/hc-email :: hcText('themed')}"></div>
                """);

        String html = Templates.render(appHome, "templates/mail/notice.html", Map.of());

        assertThat(html).contains("color:#123456").contains("themed");
    }

    private static String bundled(String name) {
        String resource = "tesseraql/templates/tql/email/" + name;
        try (InputStream in = BundledEmailTemplatesTest.class.getClassLoader()
                .getResourceAsStream(resource)) {
            assertThat(in).as(resource).isNotNull();
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw new java.io.UncheckedIOException(ex);
        }
    }

    private static Set<String> fragments(String template) {
        Matcher matcher = FRAGMENT.matcher(template);
        Set<String> names = new java.util.HashSet<>();
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        return names;
    }
}
