# Generated by the TesseraQL Studio SCIM wizard. Review and merge into config/tesseraql.yml.
# The outbound token is an environment-variable reference; never commit a literal secret.
tesseraql:
  scim:
    enabled: true
    groups:
      enabled: {{{ groups }}}
    outbound:
      enabled: {{{ outbound }}}
{{# outboundUrl }}
      target:
        url: "{{{ outboundUrl }}}"
        token: "{{{ tokenRef }}}"
{{/ outboundUrl }}
