# Generated by the TesseraQL Studio SAML SP wizard. Review and merge into config/tesseraql.yml.
tesseraql:
  saml:
    enabled: true
    sp:
      audience: "{{{ spAudience }}}"
      acsUrl: "{{{ acsUrl }}}"
{{# nameIdFormat }}
      nameIdFormat: "{{{ nameIdFormat }}}"
{{/ nameIdFormat }}
    idp:
      ssoUrl: "{{{ ssoUrl }}}"
{{# sloUrl }}
      sloUrl: "{{{ sloUrl }}}"
{{/ sloUrl }}
{{# idpMetadataPath }}
      metadata: "{{{ idpMetadataPath }}}"
{{/ idpMetadataPath }}
{{# publicKeyPath }}
      publicKey: "{{{ publicKeyPath }}}"
{{/ publicKeyPath }}
    attributes:
      loginId: "{{{ loginIdAttribute }}}"
{{# emailAttribute }}
      email: "{{{ emailAttribute }}}"
{{/ emailAttribute }}
    link:
      enabled: true
      provision: {{{ provision }}}
