# Generated by the TesseraQL Studio identity realm wizard. Review and merge into config/tesseraql.yml.
tesseraql:
  identity:
    defaultRealm: "{{{ realmId }}}"
    realms:
      {{{ realmId }}}:
        type: "{{{ type }}}"
        datasource: "{{{ datasource }}}"
{{# sqlRoot }}
        sqlRoot: "{{{ sqlRoot }}}"
{{/ sqlRoot }}
{{# userManagement }}
        capabilities:
          userManagement: "{{{ userManagement }}}"
{{/ userManagement }}
