package io.tesseraql.runtime;

import com.zaxxer.hikari.HikariDataSource;
import io.tesseraql.core.error.TqlDomain;
import io.tesseraql.core.error.TqlErrorCode;
import io.tesseraql.core.error.TqlException;
import io.tesseraql.pipeline.tenant.MainRolePools;
import io.tesseraql.pipeline.tenant.PoolRole;
import io.tesseraql.yaml.config.AppConfig;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;

/**
 * The role pools {@code main} declares (docs/capacity-defaults.md decision 5): a second pool onto
 * main's own database for every job run ({@code jobPool}), and one for the asynchronous transfers
 * a route starts ({@code fileTransferPool}).
 *
 * <p>Nothing declares one by default, and an undeclared role leaves its work on {@code main} — so
 * an application that says nothing runs exactly as before. A declared one takes main's coordinate
 * (the {@code --embedded-db} override included) and its own sizing, with every pool's keys.
 *
 * <p>Kept apart from the named datasources on purpose: a role pool is not a datasource a route can
 * name, and whatever walks the named pools — per-datasource migrations among them — must not find
 * it.
 */
final class MainRoles implements MainRolePools, AutoCloseable {

    /**
     * TQL-YAML-1115: a role pool this runtime would never use — under a datasource other than
     * {@code main}, where jobs take that datasource's own pool and transfers never run, or on a
     * {@code main} that is an in-process duckdb engine, which has no second door to open.
     */
    static final TqlErrorCode MISPLACED = new TqlErrorCode(TqlDomain.YAML, 1115);

    /** The roles a pool block may declare, in the order they are built and reported. */
    static final List<PoolRole> ROLES = List.of(PoolRole.JOBS, PoolRole.FILE_TRANSFERS);

    private final Map<PoolRole, HikariDataSource> pools;

    private MainRoles(Map<PoolRole, HikariDataSource> pools) {
        this.pools = pools;
    }

    /** The key a role's block sits under, in main's datasource block or in a tenant's. */
    static String key(PoolRole role) {
        return switch (role) {
            case JOBS -> "jobPool";
            case FILE_TRANSFERS -> "fileTransferPool";
            case ONLINE -> throw new IllegalArgumentException("the online pool is the pool itself");
        };
    }

    /** The suffix a role pool's HikariCP name carries after its owner's. */
    static String suffix(PoolRole role) {
        return switch (role) {
            case JOBS -> "jobs";
            case FILE_TRANSFERS -> "transfers";
            case ONLINE -> throw new IllegalArgumentException("the online pool is the pool itself");
        };
    }

    /**
     * Builds the role pools {@code main} declares. The keys are read with their literals at the
     * call site: the configuration reference is generated by scanning for exactly that shape.
     */
    static MainRoles create(AppConfig config, DataSources.MainDatasourceOverride override,
            ClassLoader moduleLoader) {
        Map<PoolRole, String> declared = new EnumMap<>(PoolRole.class);
        if (config.navigate("tesseraql.datasources.main.jobPool") != null) {
            declared.put(PoolRole.JOBS, "tesseraql.datasources.main.jobPool.");
        }
        if (config.navigate("tesseraql.datasources.main.fileTransferPool") != null) {
            declared.put(PoolRole.FILE_TRANSFERS, "tesseraql.datasources.main.fileTransferPool.");
        }
        Map<PoolRole, HikariDataSource> built = new EnumMap<>(PoolRole.class);
        try {
            declared.forEach((role, sizing) -> built.put(role, DataSources.createRole(config,
                    "tesseraql-main-" + suffix(role), "tesseraql.datasources.main.", override,
                    sizing, moduleLoader)));
        } catch (RuntimeException failed) {
            built.values().forEach(HikariDataSource::close);
            throw failed;
        }
        return new MainRoles(built);
    }

    /**
     * Refuses a role pool this runtime would never use, before any pool connects: under a
     * datasource other than {@code main}, or on a duckdb {@code main}.
     */
    static void refuseMisplaced(AppConfig config) {
        if (!(config.navigate("tesseraql.datasources") instanceof Map<?, ?> datasources)) {
            return;
        }
        for (Map.Entry<?, ?> entry : datasources.entrySet()) {
            if (!(entry.getValue() instanceof Map<?, ?> block)) {
                continue;
            }
            String name = String.valueOf(entry.getKey());
            List<String> roles = ROLES.stream().map(MainRoles::key)
                    .filter(block::containsKey).toList();
            if (roles.isEmpty()) {
                continue;
            }
            if (!"main".equals(name)) {
                throw new TqlException(MISPLACED, "tesseraql.datasources." + name + " declares "
                        + String.join(" and ", roles) + ", which configures nothing there: a job"
                        + " on '" + name + "' takes that datasource's own pool, and file transfers"
                        + " run only on main. A role pool is part of main"
                        + " (docs/capacity-defaults.md); declare it under"
                        + " tesseraql.datasources.main, or remove it.");
            }
            if (DuckDbDatasources.isDuckDb(config, "main")) {
                throw new TqlException(MISPLACED, "tesseraql.datasources.main is a duckdb engine"
                        + " and declares " + String.join(" and ", roles) + ": a role pool is a"
                        + " second pool onto a server database, and an in-process engine has"
                        + " none to open (docs/capacity-defaults.md). Remove the block.");
            }
        }
    }

    @Override
    public DataSource of(PoolRole role) {
        return pools.get(role);
    }

    /** Each declared role pool by the name its metrics carry: {@code main.jobPool}, and so on. */
    Map<String, HikariDataSource> byMetricName() {
        Map<String, HikariDataSource> named = new LinkedHashMap<>();
        pools.forEach((role, pool) -> named.put("main." + key(role), pool));
        return named;
    }

    @Override
    public void close() {
        pools.values().forEach(HikariDataSource::close);
    }
}
