# Generated by the TesseraQL Studio SAML SP wizard. Review and merge into config/tesseraql.yml.
tesseraql:
  saml:
    enabled: true
    sp:
      audience: "[(${spAudience})]"
      acsUrl: "[(${acsUrl})]"
[# th:if="${!#strings.isEmpty(nameIdFormat)}"]      nameIdFormat: "[(${nameIdFormat})]"
[/]    idp:
      ssoUrl: "[(${ssoUrl})]"
[# th:if="${!#strings.isEmpty(sloUrl)}"]      sloUrl: "[(${sloUrl})]"
[/][# th:if="${!#strings.isEmpty(idpMetadataPath)}"]      metadata: "[(${idpMetadataPath})]"
[/][# th:if="${!#strings.isEmpty(publicKeyPath)}"]      publicKey: "[(${publicKeyPath})]"
[/]    attributes:
      loginId: "[(${loginIdAttribute})]"
[# th:if="${!#strings.isEmpty(emailAttribute)}"]      email: "[(${emailAttribute})]"
[/]    link:
      enabled: true
      provision: [(${provision})]
