# Generated by the TesseraQL Studio identity realm wizard. Review and merge into config/tesseraql.yml.
tesseraql:
  identity:
    defaultRealm: "[(${realmId})]"
    realms:
      [(${realmId})]:
        type: "[(${type})]"
        datasource: "[(${datasource})]"
[# th:if="${!#strings.isEmpty(sqlRoot)}"]        sqlRoot: "[(${sqlRoot})]"
[/][# th:if="${!#strings.isEmpty(userManagement)}"]        capabilities:
          userManagement: "[(${userManagement})]"
[/]