# Generated by the TesseraQL Studio OIDC provider wizard. Review and merge into config/tesseraql.yml.
# For a confidential client, add the secret via the secret provider (never paste it here), e.g.
#     clientSecret: ${secret.env.OIDC_CLIENT_SECRET}
tesseraql:
  oidc:
    enabled: true
    discoveryUri: "[(${discoveryUri})]"
    clientId: "[(${clientId})]"
    redirectUri: "[(${redirectUri})]"
[# th:if="${!#strings.isEmpty(scopes)}"]    scopes: "[(${scopes})]"
[/][# th:if="${!#strings.isEmpty(postLoginUrl)}"]    postLoginUrl: "[(${postLoginUrl})]"
[/]    link:
      enabled: true
      provision: [(${provision})]
