package io.tesseraql.docs;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the committed reference pages (docs/docs-site.md): the YAML-surface
 * reference from the JSON schema and the error-code index from a source scan, written
 * as plain markdown into {@code docs/} so they are GitHub-browsable like every other
 * document and flow onto the site through the same sync. {@code GeneratedReferenceTest}
 * fails the build when the committed files drift from what these sources generate.
 *
 * <p>Refresh after changing the schema or adding error codes:
 * {@code mvn -q -pl tesseraql-docs-reference exec:java}
 */
public final class ReferenceGenerator {

    static final String BANNER = "<!-- Generated by tesseraql-docs-reference. Do not edit"
            + " by hand; refresh with: mvn -q -pl tesseraql-docs-reference exec:java -->\n";

    private ReferenceGenerator() {
    }

    /** CLI entry point: {@code ReferenceGenerator <repoRoot>}. */
    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: ReferenceGenerator <repoRoot>");
        }
        Path repoRoot = Path.of(args[0]);
        Files.writeString(repoRoot.resolve("docs/reference-yaml-surface.md"),
                yamlSurface(repoRoot));
        Files.writeString(repoRoot.resolve("docs/reference-error-codes.md"),
                errorCodes(repoRoot));
        System.out.println("reference pages regenerated under docs/");
    }

    /** The full {@code reference-yaml-surface.md} content. */
    public static String yamlSurface(Path repoRoot) throws IOException {
        return BANNER + SchemaReference.render(repoRoot
                .resolve("tesseraql-yaml/src/main/resources/schema/tesseraql-v1.schema.json"));
    }

    /** The full {@code reference-error-codes.md} content. */
    public static String errorCodes(Path repoRoot) throws IOException {
        return BANNER + ErrorIndex.render(repoRoot);
    }

    /** GitHub-slugger-compatible heading anchors, shared by both pages. */
    static String slug(String heading) {
        return heading.toLowerCase().replaceAll("[^a-z0-9 _-]", "").trim().replace(' ', '-');
    }

    /** Markdown table cells: pipes escaped, line breaks flattened. */
    static String cell(String text) {
        return text.replace("|", "\\|").replaceAll("\\s+", " ").trim();
    }
}
