version: tesseraql/v1
id: tql.iamAdmin.roles.create
kind: route
recipe: command-json

security:
  policy: tql.iam.admin.write

input:
  code:
    type: string
    required: true
  name:
    type: string
    required: false
  application:
    type: string
    required: false

steps:
  - id: main
    service:
      name: iam.createRole
      params:
        code: params.code
        name: params.name
        application: params.application
response:
  redirect:
    location: /_tesseraql/admin/roles?created=1
