package io.tesseraql.yaml.scaffold;

import java.sql.Types;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * The introspected shape of one database table (roadmap Phase 23): the input the CRUD scaffold
 * generator works from. Column order is the table's ordinal order, so generated artifacts are
 * deterministic for a given schema.
 *
 * @param name          the table name as the database reports it
 * @param columns       the columns in ordinal order
 * @param primaryKey    the primary-key column names in key-sequence order
 * @param uniqueIndexes single-column unique indexes (index name to column name, sorted by index
 *                      name) excluding the primary key; the scaffold maps them to declarative
 *                      constraint-violation errors (Phase 18)
 */
public record TableSchema(String name, List<Column> columns, List<String> primaryKey,
        Map<String, String> uniqueIndexes) {

    /** The column names conventionally stamped from the canonical audit binds (Phase 18). */
    public static final List<String> AUDIT_COLUMNS = List.of(
            "created_by", "created_at", "updated_by", "updated_at");

    /** The column name conventionally guarding updates with optimistic locking (Phase 18). */
    public static final String VERSION_COLUMN = "version";

    public TableSchema {
        columns = List.copyOf(columns);
        primaryKey = List.copyOf(primaryKey);
        uniqueIndexes = java.util.Collections
                .unmodifiableMap(new java.util.LinkedHashMap<>(uniqueIndexes));
    }

    /** The single primary-key column, or empty for composite or missing keys. */
    public Optional<Column> primaryKeyColumn() {
        if (primaryKey.size() != 1) {
            return Optional.empty();
        }
        return column(primaryKey.get(0));
    }

    /** Finds a column by name, case-insensitively. */
    public Optional<Column> column(String name) {
        return columns.stream()
                .filter(column -> column.name().equalsIgnoreCase(name))
                .findFirst();
    }

    /** The optimistic-locking column, when the table follows the Phase 18 convention. */
    public Optional<Column> versionColumn() {
        return column(VERSION_COLUMN).filter(Column::isIntegerLike);
    }

    /** Whether the named column is part of the primary key. */
    public boolean isPrimaryKey(Column column) {
        return primaryKey.stream().anyMatch(key -> key.equalsIgnoreCase(column.name()));
    }

    /** Whether the column is one of the conventional audit columns (Phase 18). */
    public boolean isAuditColumn(Column column) {
        return AUDIT_COLUMNS.contains(column.name().toLowerCase(Locale.ROOT));
    }

    /**
     * The user-editable data columns: everything that is not the primary key, the version column,
     * or an audit column. These drive the generated inputs, forms, and SQL column lists.
     */
    public List<Column> dataColumns() {
        return columns.stream()
                .filter(column -> !isPrimaryKey(column))
                .filter(column -> !isAuditColumn(column))
                .filter(column -> !column.name().equalsIgnoreCase(VERSION_COLUMN))
                .toList();
    }

    /**
     * One introspected column.
     *
     * @param name          the column name as the database reports it
     * @param jdbcType      the {@link java.sql.Types} code
     * @param typeName      the database-specific type name (informational)
     * @param size          the column size (length for character types, precision for numerics)
     * @param scale         the decimal scale, 0 when not applicable
     * @param nullable      whether the column accepts NULL
     * @param autoGenerated whether the database generates the value (identity / auto-increment)
     * @param hasDefault    whether the column declares a default expression
     */
    public record Column(String name, int jdbcType, String typeName, int size, int scale,
            boolean nullable, boolean autoGenerated, boolean hasDefault) {

        /** Maps the JDBC type to the route-input type vocabulary (design ch. 6.3, Phase 22). */
        public String inputType() {
            return switch (jdbcType) {
                case Types.TINYINT, Types.SMALLINT, Types.INTEGER, Types.BIGINT -> "integer";
                case Types.NUMERIC, Types.DECIMAL -> scale == 0 ? "integer" : "number";
                case Types.FLOAT, Types.REAL, Types.DOUBLE -> "number";
                case Types.BOOLEAN, Types.BIT -> "boolean";
                case Types.DATE -> "date";
                case Types.TIMESTAMP, Types.TIMESTAMP_WITH_TIMEZONE -> "datetime";
                default -> "string";
            };
        }

        /** Whether the column holds a character type whose length should bound the input. */
        public boolean isCharacter() {
            return switch (jdbcType) {
                case Types.CHAR, Types.VARCHAR, Types.NCHAR, Types.NVARCHAR -> true;
                default -> false;
            };
        }

        /** Whether the column holds an exact integer type (version-column candidate). */
        public boolean isIntegerLike() {
            return "integer".equals(inputType());
        }

        /** Whether a request must supply the column: NOT NULL without a database default. */
        public boolean isRequired() {
            return !nullable && !hasDefault && !autoGenerated;
        }
    }
}
