package io.tesseraql.yaml.scaffold;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.tesseraql.core.error.TqlException;
import io.tesseraql.yaml.SimpleYamlParser;
import io.tesseraql.yaml.config.AppConfig;
import io.tesseraql.yaml.config.ResponseHeaderDefaults;
import io.tesseraql.yaml.config.SecurityDefaults;
import io.tesseraql.yaml.manifest.AppManifest;
import io.tesseraql.yaml.manifest.ManifestLoader;
import io.tesseraql.yaml.model.Binding;
import io.tesseraql.yaml.model.RouteDefinition;
import java.nio.file.Path;
import java.sql.Types;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * The CRUD generator's conventions (roadmap Phase 23): Phase 18 audit and locking SQL, hc
 * markup, constraint mappings, and graceful degradation when a table opts out of them.
 */
class CrudScaffolderTest {

    private final CrudScaffolder scaffolder = new CrudScaffolder();
    private final SimpleYamlParser parser = new SimpleYamlParser();

    /** The full-convention table: identity key, version, audit columns, unique index. */
    private static TableSchema items() {
        return new TableSchema("items", List.of(
                column("id", Types.BIGINT, false, true),
                column("name", Types.VARCHAR, false, false),
                column("quantity", Types.INTEGER, false, false),
                new TableSchema.Column("unit_price", Types.NUMERIC, "numeric", 12, 2, true,
                        false, false),
                column("due_date", Types.DATE, true, false),
                column("active", Types.BOOLEAN, false, false),
                column("note", Types.VARCHAR, true, false),
                column("version", Types.BIGINT, false, false),
                column("created_by", Types.VARCHAR, false, false),
                column("created_at", Types.TIMESTAMP, false, false),
                column("updated_by", Types.VARCHAR, false, false),
                column("updated_at", Types.TIMESTAMP, false, false)),
                List.of("id"),
                Map.of("uq_items_name", "name"));
    }

    /** A bare table: assigned string key, no version, no audit columns, no string column. */
    private static TableSchema bare() {
        return new TableSchema("codes", List.of(
                new TableSchema.Column("code", Types.CHAR, "char", 8, 0, false, false, false),
                column("rank", Types.INTEGER, false, false)),
                List.of("code"),
                Map.of());
    }

    private static TableSchema.Column column(String name, int type, boolean nullable,
            boolean autoGenerated) {
        int size = type == Types.VARCHAR ? 200 : 0;
        return new TableSchema.Column(name, type, "t", size, 0, nullable, autoGenerated, false);
    }

    @Test
    void generatesTheFullCrudSliceWithParseableRoutes() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        assertThat(files).extracting(ScaffoldedFile::path).containsExactly(
                "domains/items.yml",
                "rules/items.yml",
                "rules/items-name-free.sql",
                "web/items/get.yml",
                "web/items/list.view.yml",
                "web/items/search.sql",
                "web/items/frags.html",
                "web/items/new/get.yml",
                "web/items/new/new.view.yml",
                "web/items/create/post.yml",
                "web/items/create/insert.sql",
                "web/items/{id}/get.yml",
                "web/items/{id}/select.sql",
                "web/items/{id}/edit.view.yml",
                "web/items/{id}/update/post.yml",
                "web/items/{id}/update/update.sql",
                "web/items/{id}/delete/post.yml",
                "web/items/{id}/delete/delete.sql",
                "tests/items-crud-test.yml");
        files.stream().filter(file -> file.path().endsWith(".yml"))
                .filter(file -> !file.path().startsWith("tests/"))
                .filter(file -> !file.path().startsWith("domains/"))
                .filter(file -> !file.path().startsWith("rules/"))
                .filter(file -> !file.path().endsWith(".view.yml"))
                .forEach(file -> parser.parseRoute(file.content(), file.path()));
    }

    @Test
    void createCapturesTheGeneratedKeyAndMapsUniqueConstraints() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        RouteDefinition create = parser.parseRoute(content(files, "web/items/create/post.yml"),
                "post.yml");
        assertThat(create.steps()).containsKey("record");
        assertThat(create.steps().get("record").keys()).containsExactly("id");
        // The constraint mapping lives once in the table's domains file, not per route.
        assertThat(create.errors()).isNull();
        assertThat(create.response().redirect().location())
                .isEqualTo("/items/{steps.record.keys.id}");
        assertThat(create.input()).containsKeys("name", "quantity", "unit_price", "due_date",
                "active", "note");
        // The field itself lives in the domain; the route states only its operational choice.
        assertThat(create.input().get("due_date").domain()).isEqualTo("items.due_date");
        assertThat(create.input().get("due_date").format()).isNull();
        assertThat(create.input().get("name").required()).isTrue();

        String insert = content(files, "web/items/create/insert.sql");
        assertThat(insert).doesNotContain("  id,");
        assertThat(insert).contains("/* audit.user */ 'someone'")
                .contains("/* audit.now */ '2026-01-01 00:00:00'")
                .contains("/* unit_price */ 1");
    }

    @Test
    void updatePairsTheVersionPredicateWithTheRowCountExpectation() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        RouteDefinition update = parser.parseRoute(
                content(files, "web/items/{id}/update/post.yml"), "post.yml");
        Binding statement = update.steps().get("main");
        assertThat(statement.expect().rowCount()).isEqualTo(1);
        assertThat(statement.expect().effectiveOnMismatch()).isEqualTo("conflict");
        // Binds read the coerced params.* view: raw body/path values are strings (Phase 22).
        assertThat(statement.params()).containsEntry("version", "params.version")
                .containsEntry("id", "params.id");
        assertThat(update.input().get("id").domain()).isEqualTo("items.id");
        assertThat(update.input().get("version").required()).isTrue();

        String sql = content(files, "web/items/{id}/update/update.sql");
        assertThat(sql).contains("version = version + 1")
                .contains("updated_by = /* audit.user */ 'someone'")
                .contains("and version = /* version */ 1");

        String delete = content(files, "web/items/{id}/delete/delete.sql");
        assertThat(delete).contains("and version = /* version */ 1");
    }

    @Test
    void pagesUseTheBlessedHypermediaComponentsPatterns() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        // One route serves the list: enum-constrained sort/dir + the live search input feed
        // the SQL, and the tql/view/list pattern renders (docs/declarative-views.md).
        assertThat(content(files, "web/items/get.yml"))
                .contains("recipe: query-html")
                .contains("view: items")
                // Declarative pagination (Phase 41): the framework appends the clause.
                .contains("pagination:")
                .contains("maxSize: 200")
                .contains("sort: query.sort")
                .contains("enum: [id, name, quantity, unit_price, due_date, active, note]")
                .contains("enum: [asc, desc]");
        assertThat(content(files, "web/items/list.view.yml"))
                .contains("recipe: list")
                .contains("search: q")
                .contains("sortable: true")
                .contains("text: Open")
                .contains("link: /items/{id}")
                .contains("header: frags.html::new-link");
        // The ORDER BY is a single embedded variable (whole clause in the comment → plain-runnable),
        // interpolating the enum-checked sort/dir with a primary-key tiebreaker.
        assertThat(content(files, "web/items/search.sql"))
                .contains("/*# order by t.{sort} {dir}, t.id */")
                .doesNotContain("limit")
                .doesNotContain("/*%if sort");
        // The edit view derives its fields from the update route; version rides hidden and the
        // confirmed delete mounts in the footer slot.
        assertThat(content(files, "web/items/{id}/edit.view.yml"))
                .contains("recipe: form")
                .contains("action: /items/{id}/update")
                .contains("- name: version\n    widget: hidden")
                .contains("footer: ../frags.html::confirm-delete");
    }

    @Test
    void formsFollowTheMutatingFormRecipe() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        // The create view derives every field from the create route (the tql/view/form
        // pattern renders the blessed mutating-form recipe).
        assertThat(content(files, "web/items/new/new.view.yml"))
                .contains("recipe: form")
                .contains("action: /items/create")
                .contains("header: ../frags.html::back-link");

        // The confirmed delete lives in the shared frags file, mounted by the edit view's
        // footer slot; it posts the current row's id/version off the view model.
        assertThat(content(files, "web/items/frags.html"))
                .contains("th:fragment=\"confirm-delete\"")
                // A link expression, so a scaffolded page keeps working under a base path
                // (docs/base-path.md) — and shows the author the idiom.
                .contains("hx-post=@{|/items/${v.row['id']}/delete|}")
                .contains("hx-trigger=\"hc:confirmed\"")
                .contains("data-hc-confirm=\"Delete this record?\"")
                .contains("name=\"version\" th:value=\"${v.row['version']}\"")
                .contains("<input type=\"hidden\" name=\"_csrf\" th:value=\"${_csrf}\">")
                .contains("th:fragment=\"new-link\"")
                .contains("th:fragment=\"back-link\"");
    }

    @Test
    void mutationRoutesEnableCsrfAndPagesAuthenticateToCarryTheToken() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        // The form-bearing pages authenticate, so the shell renders the CSRF meta tag they need.
        assertThat(parser.parseRoute(content(files, "web/items/get.yml"), "get.yml")
                .security().auth()).isEqualTo("browser");
        assertThat(parser.parseRoute(content(files, "web/items/new/get.yml"), "get.yml")
                .security().auth()).isEqualTo("browser");

        // Every mutation enforces CSRF.
        for (String route : List.of("web/items/create/post.yml", "web/items/{id}/update/post.yml",
                "web/items/{id}/delete/post.yml")) {
            assertThat(parser.parseRoute(content(files, route), route).security()
                    .csrfEnforced("POST")).as(route).isTrue();
        }
    }

    @Test
    void securityDefaultsSlimTheGeneratedBlocksToTheirPolicy() {
        // The app's declared defaults give /items pages browser auth and CSRF on writes
        // (docs/route-defaults.md), so the generated routes state only their policy.
        SecurityDefaults defaults = SecurityDefaults.from(new AppConfig(Map.of("tesseraql",
                Map.of("security", Map.of("defaults", Map.of("routes", List.of(
                        Map.of("match", "/**", "auth", "browser", "csrf", "auto")))))),
                name -> null));
        List<ScaffoldedFile> files = new CrudScaffolder(defaults, null).scaffold(items());

        var list = parser.parseRoute(content(files, "web/items/get.yml"), "get.yml").security();
        assertThat(list.auth()).isNull();
        assertThat(list.policy()).isEqualTo("app.read");
        var create = parser.parseRoute(content(files, "web/items/create/post.yml"), "post.yml")
                .security();
        assertThat(create.auth()).isNull();
        assertThat(create.csrf()).isNull();
        assertThat(create.policy()).isEqualTo("app.write");
        // The shared frags keep the CSRF form token: the runtime still enforces it via the
        // resolved defaults.
        assertThat(content(files, "web/items/frags.html"))
                .contains("<input type=\"hidden\" name=\"_csrf\" th:value=\"${_csrf}\">");
    }

    @Test
    void bearerOnlyDefaultsKeepTheExplicitBrowserBlocks() {
        // Defaults that would NOT reproduce the browser+CSRF posture leave the routes explicit.
        SecurityDefaults defaults = SecurityDefaults.from(new AppConfig(Map.of("tesseraql",
                Map.of("security", Map.of("defaults", Map.of("routes", List.of(
                        Map.of("match", "/**", "auth", "bearer")))))),
                name -> null));
        List<ScaffoldedFile> files = new CrudScaffolder(defaults, null).scaffold(items());

        assertThat(parser.parseRoute(content(files, "web/items/get.yml"), "get.yml")
                .security().auth()).isEqualTo("browser");
        assertThat(parser.parseRoute(content(files, "web/items/create/post.yml"), "post.yml")
                .security().csrfEnforced("POST")).isTrue();
    }

    @Test
    void declaredResponseHeaderDefaultsDropThePerRouteHeaderBlock() {
        // Without app defaults every page carries the security header block; with them, the
        // app-wide declaration sends it and the generated routes stay clean.
        assertThat(content(scaffolder.scaffold(items()), "web/items/get.yml"))
                .contains("Content-Security-Policy");

        ResponseHeaderDefaults headerDefaults = ResponseHeaderDefaults.from(new AppConfig(
                Map.of("tesseraql", Map.of("security", Map.of("responseHeaders",
                        Map.of("X-Frame-Options", "DENY")))),
                name -> null));
        List<ScaffoldedFile> slim = new CrudScaffolder(null, headerDefaults).scaffold(items());
        assertThat(content(slim, "web/items/get.yml"))
                .doesNotContain("Content-Security-Policy")
                .doesNotContain("headers:");
        assertThat(content(slim, "web/items/new/get.yml")).doesNotContain("headers:");
    }

    @Test
    void theSharedUniquenessRuleIsReferencedByCreateAndUpdate() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        assertThat(content(files, "rules/items.yml"))
                .contains("items_name_is_free:")
                .contains("binds: { name: string, excludeId: integer }")
                .contains("code: duplicate");
        assertThat(content(files, "rules/items-name-free.sql"))
                .contains("/*%if excludeId != null */")
                .contains("id <> /* excludeId */0");

        RouteDefinition create = parser.parseRoute(content(files, "web/items/create/post.yml"),
                "post.yml");
        assertThat(create.validate().get("name_is_free").use()).isEqualTo("items_name_is_free");
        assertThat(create.validate().get("name_is_free").params())
                .containsEntry("name", "params.name")
                .containsEntry("excludeId", "params.id");
        RouteDefinition update = parser.parseRoute(
                content(files, "web/items/{id}/update/post.yml"), "post.yml");
        assertThat(update.validate().get("name_is_free").params())
                .containsEntry("excludeId", "params.id");
    }

    @Test
    void foreignKeysGenerateSharedExistenceRules() {
        TableSchema table = new TableSchema("order_lines", List.of(
                new TableSchema.Column("id", Types.BIGINT, "bigint", 0, 0, false, true, false),
                column("product_id", Types.BIGINT, false, false),
                column("warehouse_id", Types.BIGINT, true, false),
                new TableSchema.Column("qty", Types.INTEGER, "int", 0, 0, false, false, false)),
                List.of("id"), Map.of(), List.of(
                        new TableSchema.ForeignKey("product_id", "products", "id"),
                        new TableSchema.ForeignKey("warehouse_id", "warehouses", "id")));
        List<ScaffoldedFile> files = scaffolder.scaffold(table);

        assertThat(content(files, "rules/order_lines.yml"))
                .contains("order_lines_product_id_exists:")
                .contains("binds: { product_id: integer }")
                .contains("order_lines_warehouse_id_exists:")
                .contains("code: unknown");
        assertThat(content(files, "rules/order_lines-product-id-exists.sql"))
                .contains("not exists (select 1 from products where id = /* product_id */0)");

        RouteDefinition create = parser.parseRoute(
                content(files, "web/order_lines/create/post.yml"), "post.yml");
        // Both write routes share the rule; the nullable FK is guarded so an absent optional
        // value never reaches the query.
        assertThat(create.validate().get("product_id_exists").use())
                .isEqualTo("order_lines_product_id_exists");
        assertThat(create.validate().get("product_id_exists").when()).isNull();
        assertThat(create.validate().get("warehouse_id_exists").when())
                .isEqualTo("params.warehouse_id != null");
        RouteDefinition update = parser.parseRoute(
                content(files, "web/order_lines/{id}/update/post.yml"), "post.yml");
        assertThat(update.validate().get("product_id_exists").use())
                .isEqualTo("order_lines_product_id_exists");
    }

    @Test
    void theDomainsFileCarriesTheDdlDerivedKnowledgeOnce() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        String domains = content(files, "domains/items.yml");
        assertThat(domains)
                .contains("items.name:")
                .contains("maxLength: 200")
                .contains("items.due_date:")
                .contains("format: yyyy-MM-dd")
                .contains("items.version:")
                // The constraint catalog moved here from the per-route errors blocks.
                .contains("constraints:")
                .contains("uq_items_name:")
                .contains("field: name");

        // Every emitted domain is referenced by at least one generated route (no TQL-FIELD-4611).
        String allRoutes = files.stream()
                .filter(file -> file.path().endsWith(".yml") && file.path().startsWith("web/"))
                .map(ScaffoldedFile::content)
                .reduce("", String::concat);
        java.util.regex.Matcher names = java.util.regex.Pattern.compile("  (items\\.\\w+):")
                .matcher(domains);
        while (names.find()) {
            assertThat(allRoutes).as(names.group(1)).contains("domain: " + names.group(1));
        }
    }

    @Test
    void suiteExercisesBothSearchBranchesAndTheDetailSelect() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        String suite = content(files, "tests/items-crud-test.yml");
        assertThat(suite).contains("web/items/search.sql")
                .contains("q: no-such-row")
                .contains("web/items/{id}/select.sql")
                .contains("id: -1");
    }

    @Test
    void scaffoldAppliedToASkeletonLoadsAsAManifest(@TempDir Path target) {
        AppScaffolder apps = new AppScaffolder();
        Path home = target.resolve("demo");
        apps.writeNew(home, apps.scaffold("demo"));

        ScaffoldWriter.Report report = new ScaffoldWriter().apply(home,
                scaffolder.scaffold(items()), false);

        assertThat(report.blocked()).isFalse();
        AppManifest manifest = new ManifestLoader().load(home);
        assertThat(manifest.routes()).hasSize(8);
    }

    @Test
    void tablesWithoutTheConventionsDegradeGracefully() {
        List<ScaffoldedFile> files = scaffolder.scaffold(bare());

        // Assigned key: the form carries it and the redirect reads it from the body.
        RouteDefinition create = parser.parseRoute(content(files, "web/codes/create/post.yml"),
                "post.yml");
        // No generated key to capture, so the insert needs no keys: — but it is still a step,
        // because a command has one spelling whatever its statement count.
        assertThat(create.steps().get("main").keys()).isEmpty();
        assertThat(create.input()).containsKey("code");
        assertThat(create.response().redirect().location()).isEqualTo("/codes/{params.code}");

        // No version column: no locking predicate, no expectation (lint pairing TQL-SQL-2105).
        RouteDefinition update = parser.parseRoute(
                content(files, "web/codes/{code}/update/post.yml"), "post.yml");
        assertThat(update.steps().get("main").expect()).isNull();
        assertThat(content(files, "web/codes/{code}/update/update.sql"))
                .doesNotContain("version");

        // No character data column: no live-search filter (no q input, no search: key),
        // though the headers still sort (the ORDER BY allowlists the data columns).
        String bareSearch = content(files, "web/codes/search.sql");
        assertThat(bareSearch).doesNotContain("like").doesNotContain("q != null");
        assertThat(bareSearch).contains("/*# order by t.{sort} {dir}, t.code */");
        assertThat(content(files, "web/codes/get.yml")).doesNotContain("q:");
        assertThat(content(files, "web/codes/list.view.yml")).doesNotContain("search:");
    }

    @Test
    void aTableWithoutAPrimaryKeyIsRejectedWithAClearError() {
        TableSchema heap = new TableSchema("heap", List.of(
                column("a", Types.INTEGER, false, false)),
                List.of(), Map.of());

        assertThatThrownBy(() -> scaffolder.scaffold(heap))
                .isInstanceOf(TqlException.class)
                .hasMessageContaining("TQL-APP-5203")
                .hasMessageContaining("needs a primary key");
    }

    /** A composite key: two assigned integer columns, one unique index for the rule shape. */
    private static TableSchema pairs() {
        return new TableSchema("pairs", List.of(
                column("order_id", Types.INTEGER, false, false),
                column("line_no", Types.INTEGER, false, false),
                column("label", Types.VARCHAR, false, false)),
                List.of("order_id", "line_no"),
                Map.of("uq_pairs_label", "label"));
    }

    @Test
    void aCompositeKeyScaffoldsNestedPathsAndAndJoinedPredicates() {
        List<ScaffoldedFile> files = scaffolder.scaffold(pairs());

        // docs/list-surface.md decision 4: nested path segments, one per key column.
        assertThat(files).extracting(ScaffoldedFile::path)
                .contains("web/pairs/{order_id}/{line_no}/get.yml",
                        "web/pairs/{order_id}/{line_no}/update/post.yml",
                        "web/pairs/{order_id}/{line_no}/delete/post.yml");
        for (ScaffoldedFile file : files) {
            if (file.path().endsWith(".yml") && file.path().startsWith("web/")
                    && !file.path().endsWith(".view.yml")) {
                parser.parseRoute(file.content(), file.path());
            }
        }
        assertThat(content(files, "web/pairs/list.view.yml"))
                .contains("key: [order_id, line_no]")
                .contains("link: /pairs/{order_id}/{line_no}");
        assertThat(content(files, "web/pairs/{order_id}/{line_no}/select.sql"))
                .contains("t.order_id = /* order_id */ 1")
                .contains("and t.line_no = /* line_no */ 1");
        assertThat(content(files, "web/pairs/{order_id}/{line_no}/update/post.yml"))
                .contains("order_id: params.order_id")
                .contains("line_no: params.line_no")
                .contains("location: /pairs/{path.order_id}/{path.line_no}");
        assertThat(content(files, "web/pairs/{order_id}/{line_no}/delete/delete.sql"))
                .contains("order_id = /* order_id */ 1")
                .contains("and line_no = /* line_no */ 1");
        assertThat(content(files, "web/pairs/frags.html"))
                .contains("${v.row['order_id']}/${v.row['line_no']}/delete");
        // The unique rule excludes the row being updated by the whole key tuple.
        assertThat(content(files, "rules/pairs-label-free.sql"))
                .contains("/*%if exclude_order_id != null */")
                .contains("and not (order_id = /* exclude_order_id */1"
                        + " and line_no = /* exclude_line_no */1)");
        assertThat(content(files, "rules/pairs.yml"))
                .contains("exclude_order_id: integer")
                .contains("exclude_line_no: integer");
        assertThat(content(files, "tests/pairs-crud-test.yml"))
                .contains("order_id: -1")
                .contains("line_no: -1");
    }

    @Test
    void theListViewDeclaresThePageFrameAndItsKey() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());
        assertThat(content(files, "web/items/list.view.yml"))
                .contains("key: id");
    }

    @Test
    void generationIsDeterministic() {
        List<ScaffoldedFile> first = scaffolder.scaffold(items());
        List<ScaffoldedFile> second = scaffolder.scaffold(items());
        assertThat(second).isEqualTo(first);
    }

    private static String content(List<ScaffoldedFile> files, String path) {
        return files.stream().filter(file -> file.path().equals(path)).findFirst()
                .orElseThrow().content();
    }

    @Test
    void aMaintenanceScreenForACatalogTableInvalidatesIt() {
        // docs/lookups.md decision 13: the scaffolder knows the table it is generating for, so
        // it declares the invalidation rather than leaving a screen that saves a code and then
        // shows the old names until the hold expires.
        List<ScaffoldedFile> files = new CrudScaffolder(null, null, java.util.Set.of("items"))
                .scaffold(items());
        assertThat(content(files, "web/items/create/post.yml"))
                .contains("invalidates: [items]");
        assertThat(content(files, "web/items/{id}/update/post.yml"))
                .contains("invalidates: [items]");
        // A table no catalog reads gets nothing: emitting a declaration the linter would warn
        // about (TQL-FIELD-4620) is worse than emitting none.
        List<ScaffoldedFile> plain = new CrudScaffolder().scaffold(items());
        assertThat(content(plain, "web/items/create/post.yml")).doesNotContain("invalidates:");
    }
}
