package io.tesseraql.yaml.scaffold;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.tesseraql.core.error.TqlException;
import io.tesseraql.yaml.SimpleYamlParser;
import io.tesseraql.yaml.manifest.AppManifest;
import io.tesseraql.yaml.manifest.ManifestLoader;
import io.tesseraql.yaml.model.RouteDefinition;
import java.nio.file.Path;
import java.sql.Types;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * The CRUD generator's conventions (roadmap Phase 23): Phase 18 audit and locking SQL, hc
 * markup, constraint mappings, and graceful degradation when a table opts out of them.
 */
class CrudScaffolderTest {

    private final CrudScaffolder scaffolder = new CrudScaffolder();
    private final SimpleYamlParser parser = new SimpleYamlParser();

    /** The full-convention table: identity key, version, audit columns, unique index. */
    private static TableSchema items() {
        return new TableSchema("items", List.of(
                column("id", Types.BIGINT, false, true),
                column("name", Types.VARCHAR, false, false),
                column("quantity", Types.INTEGER, false, false),
                new TableSchema.Column("unit_price", Types.NUMERIC, "numeric", 12, 2, true,
                        false, false),
                column("due_date", Types.DATE, true, false),
                column("active", Types.BOOLEAN, false, false),
                column("note", Types.VARCHAR, true, false),
                column("version", Types.BIGINT, false, false),
                column("created_by", Types.VARCHAR, false, false),
                column("created_at", Types.TIMESTAMP, false, false),
                column("updated_by", Types.VARCHAR, false, false),
                column("updated_at", Types.TIMESTAMP, false, false)),
                List.of("id"),
                Map.of("uq_items_name", "name"));
    }

    /** A bare table: assigned string key, no version, no audit columns, no string column. */
    private static TableSchema bare() {
        return new TableSchema("codes", List.of(
                new TableSchema.Column("code", Types.CHAR, "char", 8, 0, false, false, false),
                column("rank", Types.INTEGER, false, false)),
                List.of("code"),
                Map.of());
    }

    private static TableSchema.Column column(String name, int type, boolean nullable,
            boolean autoGenerated) {
        int size = type == Types.VARCHAR ? 200 : 0;
        return new TableSchema.Column(name, type, "t", size, 0, nullable, autoGenerated, false);
    }

    @Test
    void generatesTheFullCrudSliceWithParseableRoutes() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        assertThat(files).extracting(ScaffoldedFile::path).containsExactly(
                "web/items/get.yml",
                "web/items/index.html",
                "web/items/fragments/table/get.yml",
                "web/items/fragments/table/search.sql",
                "web/items/fragments/table/table.html",
                "web/items/new/get.yml",
                "web/items/new/new.html",
                "web/items/create/post.yml",
                "web/items/create/insert.sql",
                "web/items/{id}/get.yml",
                "web/items/{id}/select.sql",
                "web/items/{id}/edit.html",
                "web/items/{id}/update/post.yml",
                "web/items/{id}/update/update.sql",
                "web/items/{id}/delete/post.yml",
                "web/items/{id}/delete/delete.sql",
                "tests/items-crud-test.yml");
        files.stream().filter(file -> file.path().endsWith(".yml"))
                .filter(file -> !file.path().startsWith("tests/"))
                .forEach(file -> parser.parseRoute(file.content(), file.path()));
    }

    @Test
    void createCapturesTheGeneratedKeyAndMapsUniqueConstraints() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        RouteDefinition create = parser.parseRoute(content(files, "web/items/create/post.yml"),
                "post.yml");
        assertThat(create.steps()).containsKey("record");
        assertThat(create.steps().get("record").keys()).containsExactly("id");
        assertThat(create.errors().constraints()).containsKey("uq_items_name");
        assertThat(create.response().redirect().location())
                .isEqualTo("/items/{steps.record.keys.id}");
        assertThat(create.input()).containsKeys("name", "quantity", "unitPrice", "dueDate",
                "active", "note");
        assertThat(create.input().get("dueDate").format()).isEqualTo("yyyy-MM-dd");

        String insert = content(files, "web/items/create/insert.sql");
        assertThat(insert).doesNotContain("  id,");
        assertThat(insert).contains("/* audit.user */ 'someone'")
                .contains("/* audit.now */ '2026-01-01 00:00:00'")
                .contains("/* unitPrice */ 1");
    }

    @Test
    void updatePairsTheVersionPredicateWithTheRowCountExpectation() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        RouteDefinition update = parser.parseRoute(
                content(files, "web/items/{id}/update/post.yml"), "post.yml");
        assertThat(update.sql().expect().rows()).isEqualTo(1);
        assertThat(update.sql().expect().effectiveOnMismatch()).isEqualTo("conflict");
        // Binds read the coerced params.* view: raw body/path values are strings (Phase 22).
        assertThat(update.sql().params()).containsEntry("version", "params.version")
                .containsEntry("id", "params.id");
        assertThat(update.input().get("id").type()).isEqualTo("integer");
        assertThat(update.input().get("version").required()).isTrue();

        String sql = content(files, "web/items/{id}/update/update.sql");
        assertThat(sql).contains("version = version + 1")
                .contains("updated_by = /* audit.user */ 'someone'")
                .contains("and version = /* version */ 1");

        String delete = content(files, "web/items/{id}/delete/delete.sql");
        assertThat(delete).contains("and version = /* version */ 1");
    }

    @Test
    void pagesUseTheBlessedHypermediaComponentsPatterns() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        assertThat(content(files, "web/items/index.html"))
                .contains("~{tql/shell :: shell(")
                .contains("hx-get=\"/items/fragments/table\"")
                .contains("hx-trigger=\"input changed delay:300ms, search\"");
        assertThat(content(files, "web/items/fragments/table/table.html"))
                .contains("class=\"hc-table\"")
                .doesNotContain("<html");
        String edit = content(files, "web/items/{id}/edit.html");
        assertThat(edit)
                .contains("class=\"hc-datepicker\" id=\"field-due-date\" type=\"date\"")
                .contains("<input type=\"hidden\" name=\"version\" th:value=\"${r.version}\">")
                .contains("class=\"hc-checkbox\"");
        // The unchecked-checkbox fallback: the hidden false is overridden by the checked value.
        assertThat(edit).contains("type=\"hidden\" name=\"active\" value=\"false\"");
    }

    @Test
    void formsFollowTheMutatingFormRecipe() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        String create = content(files, "web/items/new/new.html");
        // htmx post + an in-form error container + the double-submit guard, keeping method/action
        // for the no-JS fallback, with the hidden CSRF field.
        assertThat(create)
                .contains("method=\"post\" action=\"/items/create\"")
                .contains("hx-post=\"/items/create\"")
                .contains("hx-target=\"#items-create-form-errors\"")
                .contains("hx-disabled-elt=\"find button[type=submit]\"")
                .contains("hx-indicator=\"find .hc-spinner\"")
                .contains("<div id=\"items-create-form-errors\"></div>")
                .contains("<input type=\"hidden\" name=\"_csrf\" th:value=\"${_csrf}\">")
                .contains("<span class=\"hc-spinner htmx-indicator\"");

        String edit = content(files, "web/items/{id}/edit.html");
        // The update form posts via a dynamic hx-post; the delete form fires on the confirm event.
        assertThat(edit)
                .contains("th:attr=\"hx-post=|/items/${r.id}/update|\"")
                .contains("hx-target=\"#items-update-form-errors\"")
                .contains("th:attr=\"hx-post=|/items/${r.id}/delete|\"")
                .contains("hx-trigger=\"hc:confirmed\"")
                .contains("data-hc-confirm=\"Delete this record?\"")
                .contains("<input type=\"hidden\" name=\"_csrf\" th:value=\"${_csrf}\">");
    }

    @Test
    void mutationRoutesEnableCsrfAndPagesAuthenticateToCarryTheToken() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        // The form-bearing pages authenticate, so the shell renders the CSRF meta tag they need.
        assertThat(parser.parseRoute(content(files, "web/items/get.yml"), "get.yml")
                .security().auth()).isEqualTo("browser");
        assertThat(parser.parseRoute(content(files, "web/items/new/get.yml"), "get.yml")
                .security().auth()).isEqualTo("browser");

        // Every mutation enforces CSRF.
        for (String route : List.of("web/items/create/post.yml", "web/items/{id}/update/post.yml",
                "web/items/{id}/delete/post.yml")) {
            assertThat(parser.parseRoute(content(files, route), route).security().csrf())
                    .as(route).isTrue();
        }
    }

    @Test
    void suiteExercisesBothSearchBranchesAndTheDetailSelect() {
        List<ScaffoldedFile> files = scaffolder.scaffold(items());

        String suite = content(files, "tests/items-crud-test.yml");
        assertThat(suite).contains("web/items/fragments/table/search.sql")
                .contains("q: no-such-row")
                .contains("web/items/{id}/select.sql")
                .contains("id: -1");
    }

    @Test
    void scaffoldAppliedToASkeletonLoadsAsAManifest(@TempDir Path target) {
        AppScaffolder apps = new AppScaffolder();
        Path home = target.resolve("demo");
        apps.writeNew(home, apps.scaffold("demo"));

        ScaffoldWriter.Report report = new ScaffoldWriter().apply(home,
                scaffolder.scaffold(items()), false);

        assertThat(report.blocked()).isFalse();
        AppManifest manifest = new ManifestLoader().load(home);
        assertThat(manifest.routes()).hasSize(9);
    }

    @Test
    void tablesWithoutTheConventionsDegradeGracefully() {
        List<ScaffoldedFile> files = scaffolder.scaffold(bare());

        // Assigned key: the form carries it and the redirect reads it from the body.
        RouteDefinition create = parser.parseRoute(content(files, "web/codes/create/post.yml"),
                "post.yml");
        assertThat(create.steps()).isEmpty();
        assertThat(create.input()).containsKey("code");
        assertThat(create.response().redirect().location()).isEqualTo("/codes/{params.code}");

        // No version column: no locking predicate, no expectation (lint pairing TQL-SQL-2105).
        RouteDefinition update = parser.parseRoute(
                content(files, "web/codes/{code}/update/post.yml"), "post.yml");
        assertThat(update.sql().expect()).isNull();
        assertThat(content(files, "web/codes/{code}/update/update.sql"))
                .doesNotContain("version");

        // No character data column: the list page has no live-search branch at all.
        assertThat(content(files, "web/codes/fragments/table/search.sql"))
                .doesNotContain("%if");
        assertThat(content(files, "web/codes/new/new.html")).doesNotContain("hc-datepicker");
    }

    @Test
    void compositeKeysAreRejectedWithAClearError() {
        TableSchema pairs = new TableSchema("pairs", List.of(
                column("a", Types.INTEGER, false, false),
                column("b", Types.INTEGER, false, false)),
                List.of("a", "b"), Map.of());

        assertThatThrownBy(() -> scaffolder.scaffold(pairs))
                .isInstanceOf(TqlException.class)
                .hasMessageContaining("TQL-APP-5203")
                .hasMessageContaining("single-column primary key");
    }

    @Test
    void generationIsDeterministic() {
        List<ScaffoldedFile> first = scaffolder.scaffold(items());
        List<ScaffoldedFile> second = scaffolder.scaffold(items());
        assertThat(second).isEqualTo(first);
    }

    private static String content(List<ScaffoldedFile> files, String path) {
        return files.stream().filter(file -> file.path().equals(path)).findFirst()
                .orElseThrow().content();
    }
}
