package io.tesseraql.yaml.scaffold;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.tesseraql.core.error.TqlException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Introspection unit tests against H2 (roadmap Phase 23). The PostgreSQL path is exercised
 * end-to-end by the scaffold dogfood integration test in the Maven plugin module.
 */
class TableIntrospectorTest {

    static Connection connection;

    @BeforeAll
    static void createSchema() throws Exception {
        connection = DriverManager.getConnection("jdbc:h2:mem:introspector;DB_CLOSE_DELAY=-1");
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table items (
                      id bigint generated always as identity primary key,
                      name varchar(200) not null,
                      quantity integer not null default 0,
                      unit_price numeric(12, 2),
                      due_date date,
                      active boolean not null default true,
                      note varchar(1000),
                      version bigint not null default 1,
                      created_by varchar(200) not null,
                      created_at timestamp not null,
                      updated_by varchar(200) not null,
                      updated_at timestamp not null
                    )""");
            statement.execute("create unique index uq_items_name on items (name)");
            statement.execute("create table pairs (a int, b int, primary key (a, b))");
        }
    }

    @AfterAll
    static void close() throws Exception {
        connection.close();
    }

    @Test
    void readsColumnsInOrdinalOrderWithTypesAndConstraints() {
        TableSchema schema = new TableIntrospector().introspect(connection, "items");

        assertThat(schema.columns()).extracting(TableSchema.Column::name)
                .containsExactly("ID", "NAME", "QUANTITY", "UNIT_PRICE", "DUE_DATE", "ACTIVE",
                        "NOTE", "VERSION", "CREATED_BY", "CREATED_AT", "UPDATED_BY", "UPDATED_AT");

        TableSchema.Column id = schema.column("id").orElseThrow();
        assertThat(id.autoGenerated()).isTrue();
        assertThat(id.inputType()).isEqualTo("integer");

        TableSchema.Column name = schema.column("name").orElseThrow();
        assertThat(name.inputType()).isEqualTo("string");
        assertThat(name.isCharacter()).isTrue();
        assertThat(name.size()).isEqualTo(200);
        assertThat(name.isRequired()).isTrue();

        // NOT NULL with a database default does not force the request to supply the value.
        assertThat(schema.column("quantity").orElseThrow().isRequired()).isFalse();
        assertThat(schema.column("unit_price").orElseThrow().inputType()).isEqualTo("number");
        assertThat(schema.column("due_date").orElseThrow().inputType()).isEqualTo("date");
        assertThat(schema.column("active").orElseThrow().inputType()).isEqualTo("boolean");
        assertThat(schema.column("created_at").orElseThrow().inputType()).isEqualTo("datetime");
    }

    @Test
    void classifiesKeyVersionAuditAndDataColumns() {
        TableSchema schema = new TableIntrospector().introspect(connection, "items");

        assertThat(schema.primaryKey()).containsExactly("ID");
        assertThat(schema.primaryKeyColumn()).isPresent();
        assertThat(schema.versionColumn()).isPresent();
        assertThat(schema.isAuditColumn(schema.column("created_by").orElseThrow())).isTrue();
        assertThat(schema.dataColumns()).extracting(TableSchema.Column::name)
                .containsExactly("NAME", "QUANTITY", "UNIT_PRICE", "DUE_DATE", "ACTIVE", "NOTE");
    }

    @Test
    void capturesSingleColumnUniqueIndexesExcludingThePrimaryKey() {
        TableSchema schema = new TableIntrospector().introspect(connection, "items");

        assertThat(schema.uniqueIndexes()).containsExactly(
                java.util.Map.entry("UQ_ITEMS_NAME", "NAME"));
    }

    @Test
    void resolvesTableNamesCaseInsensitively() {
        // H2 folds unquoted identifiers to upper case; the lowercased query name still resolves.
        TableSchema schema = new TableIntrospector().introspect(connection, "ITEMS");
        assertThat(schema.name()).isEqualTo("ITEMS");
        assertThat(new TableIntrospector().introspect(connection, "items").name())
                .isEqualTo("ITEMS");
    }

    @Test
    void compositePrimaryKeysAreReportedNotCollapsed() {
        TableSchema schema = new TableIntrospector().introspect(connection, "pairs");
        assertThat(schema.primaryKey()).containsExactly("A", "B");
        assertThat(schema.primaryKeyColumn()).isEmpty();
    }

    @Test
    void unknownTableFailsWithTheScaffoldErrorCode() {
        assertThatThrownBy(() -> new TableIntrospector().introspect(connection, "nope"))
                .isInstanceOf(TqlException.class)
                .hasMessageContaining("TQL-APP-5201")
                .hasMessageContaining("nope");
    }
}
